spring:
  datasource:
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/development_formservice_test
    username: root
    password: root

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-main.yaml

mybatis:
  typeAliasesPackage: com.heliant.formservice.domain